config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/users/sign_in')

  devise_for :users

  namespace :private_panel do
    root 'homes#index'

    resources :homes, only: :index
    resources :settings, only: :index
    resource :qr_code, only: :show

    resource :otp_checks, only: [:new, :create]

    namespace :settings do
      resource :one_time_password, only: [:new, :create, :destroy] do
        get :intro
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :registerable, :database_authenticatable,
         :rememberable, :validatable,
         :two_factor_authenticatable,
         otp_secret_encryption_key: ENV['2FA_OTP_SECRET_ENCRYPTION_KEY']

  def otp_provisioning_full_url
    issuer = Rails.application.class.name

    otp_provisioning_uri("#{issuer}:#{email}", issuer: issuer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:otp_attempt])
  end

  private

  def after_sign_in_path_for(resource)
    private_panel_root_path
  end
end

app/controllers/private_panel/base_controller.rb
module PrivatePanel
  class BaseController < ::ApplicationController
    layout 'private_panel'

    before_action :authenticate_user!
    before_action :check_otp!

    private

    def check_otp!
      if current_user.otp_required_for_login? && !session[:otp_checked]
        redirect_to new_private_panel_otp_checks_path
      end
    end
  end
end

app/controllers/private_panel/homes_controller.rb
module PrivatePanel
  class HomesController < ::PrivatePanel::BaseController
    def index

    end
  end
end

app/controllers/private_panel/otp_checks_controller.rb
module PrivatePanel
  class OtpChecksController < ::PrivatePanel::BaseController
    layout 'application'

    skip_before_action :check_otp!

    def new
      @form = ::PrivatePanel::OtpCheckForm.new
    end

    def create
      @form = ::PrivatePanel::OtpCheckForm.new(
        permitted_params.merge(user: current_user)
      )

      if @form.valid?
        session[:otp_checked] = true
        redirect_to private_panel_root_path
      else
        flash[:alert] = 'Authenticator App code invalid, please try again'
        render :new
      end
    end

    private

    def permitted_params
      params.require(:form).permit(:code)
    end
  end
end

app/controllers/private_panel/qr_codes_controller.rb
module PrivatePanel
  class QrCodesController < ::PrivatePanel::BaseController
    layout false

    def show
      respond_to do |format|
        format.svg  { render body: RQRCode::QRCode.new(current_user.otp_provisioning_full_url).as_svg }
      end
    end
  end
end

app/controllers/private_panel/settings/base_controller.rb
module PrivatePanel
  module Settings
    class BaseController < ::PrivatePanel::BaseController
    end
  end
end

app/controllers/private_panel/settings/one_time_passwords_controller.rb
module PrivatePanel
  module Settings
    class OneTimePasswordsController < ::PrivatePanel::Settings::BaseController
      def intro
      end

      def new
        current_user.update(otp_secret: User.generate_otp_secret)
        current_user.save!

        @form = PrivatePanel::Settings::OneTimePasswordForm.new
      end

      def create
        @form = PrivatePanel::Settings::OneTimePasswordForm.new(
          permitted_params.merge(user: current_user)
        )

        if @form.valid?
          current_user.update(otp_required_for_login: true)

          flash[:notice] = '2FA successfully configured! Next time you login we will required the 2FA code'
          session[:otp_checked] = true
          redirect_to private_panel_settings_path
        else
          flash[:alert] = 'Something went wrong during OTP check'
          render :new
        end
      end

      def destroy
        current_user.update(otp_required_for_login: false)

        flash[:notice] = 'OTP successfully disabled!'

        redirect_to private_panel_settings_path
      end

      private

      def permitted_params
        params.require(:form).permit([:code])
      end
    end
  end
end

app/controllers/private_panel/settings_controller.rb
module PrivatePanel
  class SettingsController < ::PrivatePanel::BaseController
    def index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwoFactorPoc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="panel panel-default public-panel col-md-offset-2 col-md-8">
          <div class="panel-body">
            <h1>Two-factor POC</h1>

            <%= render partial: 'shared/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/private_panel.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwoFactorPoc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="bs-docs-nav navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Home', private_panel_root_path, class: 'navbar-brand' %>
        </div>
        <nav class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Settings", private_panel_settings_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container bs-docs-container">
      <div class="row">
        <%= render partial: 'shared/messages' %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/private_panel/homes/index.html.erb
<h1>Home</h1>

app/views/private_panel/otp_checks/new.html.erb
<h2>Two-factor authentication</h2>

<%= simple_form_for @form, as: :form, url: private_panel_otp_checks_path do |f| %>
  <%= f.input :code, required: true %>
  <%= f.button :submit, 'Verify!' %>
<% end %>

app/views/private_panel/settings/index.html.erb
<div class="row">
  <h1>Settings</h1>
</div>

<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading"><b>Two-factor methods</b></div>

    <ul class="list-group">
      <li class="list-group-item">
        <div class="row">
          <div class="col-md-6">
            Authenticator app: <b><%= current_user.otp_required_for_login? ? 'Enabled' : 'Disabled' %></b>
          </div>

          <div class="col-md-6">
            <div class="pull-right">
              <% if current_user.otp_required_for_login? %>

                <%= link_to "Disable", private_panel_settings_one_time_password_path, method: :delete, data: { confirm: 'Are you sure?' } %>

              <% else current_user.otp_required_for_login? %>

                <%= link_to "Enable", intro_private_panel_settings_one_time_password_path %>

              <% end %>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/private_panel/settings/one_time_passwords/intro.html.erb
<div class="row">
  <h1>How to setup 2 Factor Authentication using an App</h1>
</div>

<div class="row">
  <h2>Different types of 2FA explanation...</h2>
</div>

<div class="row">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<div class="row">
  <hr/>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>How do you prefer to receive the Authenticator App Code?</h2>
  </div>

  <div class="col-md-6">
    <h3>I like QRCodes!</h3>

    <p>Nice, we too!</p>

    <%= link_to new_private_panel_settings_one_time_password_path do %>
      <div class="btn btn-success btn-block">
        Check QRCode right here!
      </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <h3>I like SMS!</h3>

    <p>Not available yet...</p>
  </div>
</div>

app/views/private_panel/settings/one_time_passwords/new.html.erb
<div class="row">
  <h1>Setup with QRCode</h1>
</div>

<div class="row">
  <div class="col-md-6">
    <h2>First, scan the QRCode below: </h2>
    <%= image_tag private_panel_qr_code_path(format: :svg), class: 'qrcode' %>
  </div>

  <div class="col-md-6">
    <h2>Now, let's check if everything is ok!</h2>

    <%= simple_form_for @form, as: :form, url: private_panel_settings_one_time_password_path do |f| %>
      <%= f.input :code, required: true %>
      <%= f.button :submit, 'Check code!' %>
    <% end %>
  </div>
</div>

app/views/private_panel/settings/one_time_passwords/show.html.erb
<h1>OTP registered successfully!</h1>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>